# Generated by Django 5.0.2 on 2025-07-10 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TarotDeck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название колоды"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decks",
                        to="projects.project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Колода Таро",
                "verbose_name_plural": "Колоды Таро",
                "unique_together": {("name", "project")},
            },
        ),
        migrations.CreateModel(
            name="TarotCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название карты"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="tarot/cards/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "meaning_upright",
                    models.TextField(blank=True, verbose_name="Значение (прямое)"),
                ),
                (
                    "meaning_reversed",
                    models.TextField(
                        blank=True, verbose_name="Значение (перевернутое)"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Порядок в колоде"
                    ),
                ),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="tarot.tarotdeck",
                        verbose_name="Колода",
                    ),
                ),
            ],
            options={
                "verbose_name": "Карта Таро",
                "verbose_name_plural": "Карты Таро",
                "ordering": ["deck", "order"],
                "unique_together": {("deck", "name")},
            },
        ),
        migrations.CreateModel(
            name="TarotSpread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Название расклада"),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "num_cards",
                    models.PositiveIntegerField(verbose_name="Количество карт"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="spreads",
                        to="projects.project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Расклад Таро",
                "verbose_name_plural": "Расклады Таро",
                "unique_together": {("project", "name")},
            },
        ),
        migrations.CreateModel(
            name="Interpretation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ai_response", models.TextField(verbose_name="AI-ответ")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Дата"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interpretations",
                        to="users.userprofile",
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "cards",
                    models.ManyToManyField(to="tarot.tarotcard", verbose_name="Карты"),
                ),
                (
                    "spread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interpretations",
                        to="tarot.tarotspread",
                        verbose_name="Расклад",
                    ),
                ),
            ],
            options={
                "verbose_name": "Интерпретация",
                "verbose_name_plural": "Интерпретации",
                "ordering": ["-created_at"],
            },
        ),
    ]
