# Generated by Django 5.0.2 on 2025-07-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tarot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="interpretation",
            name="user_question",
            field=models.TextField(
                blank=True, null=True, verbose_name="Вопрос пользователя"
            ),
        ),
    ]
