# Generated by Django 5.0.2 on 2025-07-10 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "telegram_user_id",
                    models.BigIntegerField(
                        db_index=True, verbose_name="Telegram user id"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Telegram username",
                    ),
                ),
                (
                    "balance",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Баланс (раскладов)"
                    ),
                ),
                (
                    "subscription_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="Начало подписки"
                    ),
                ),
                (
                    "subscription_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="Конец подписки"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлен"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="projects.project",
                        verbose_name="Проект",
                    ),
                ),
            ],
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
                "unique_together": {("project", "telegram_user_id")},
            },
        ),
    ]
