# Generated by Django 5.0.2 on 2025-07-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="balance",
            field=models.PositiveIntegerField(
                default=5, verbose_name="Баланс (раскладов)"
            ),
        ),
    ]
